# Generated by Django 3.2.25 on 2024-10-16 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collegeName', models.CharField(max_length=50)),
                ('collegeAddress', models.CharField(max_length=50)),
                ('collegeState', models.CharField(max_length=50)),
                ('collegeCity', models.CharField(max_length=20)),
                ('collegePhoneNumber', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'sos_college',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=50)),
                ('courseDescription', models.CharField(max_length=100)),
                ('courseDuration', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'sos_course',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dob', models.DateField(max_length=20)),
                ('mobile', models.BigIntegerField(default=0)),
                ('expertise', models.CharField(max_length=50)),
                ('eid', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'sos_doctor',
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('dob', models.DateField(max_length=20)),
                ('college_ID', models.IntegerField()),
                ('collegeName', models.CharField(max_length=50)),
                ('subject_ID', models.IntegerField()),
                ('subjectName', models.CharField(max_length=50)),
                ('course_ID', models.IntegerField()),
                ('courseName', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'sos_faculty',
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openDate', models.DateField(max_length=20)),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('assignTo', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('sid', models.IntegerField(default=0)),
                ('aid', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'sos_issue',
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=20)),
                ('contactName', models.CharField(max_length=50)),
                ('mobile', models.BigIntegerField(default=0)),
                ('status', models.CharField(max_length=50)),
                ('sid', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'sos_lead',
            },
        ),
        migrations.CreateModel(
            name='Marksheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollNumber', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('physics', models.IntegerField()),
                ('chemistry', models.IntegerField()),
                ('maths', models.IntegerField()),
            ],
            options={
                'db_table': 'sos_marksheet',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('product', models.CharField(max_length=50)),
                ('date', models.DateField(max_length=20)),
                ('amount', models.IntegerField(default=0)),
                ('pid', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'sos_order',
            },
        ),
        migrations.CreateModel(
            name='PortfolioManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolioName', models.CharField(max_length=50)),
                ('initialInvestmentAmount', models.BigIntegerField(default=0)),
                ('riskToleranceLevel', models.CharField(max_length=50)),
                ('investmentStrategy', models.CharField(max_length=250)),
                ('rid', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'sos_portfoliomanagement',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'sos_role',
            },
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('product', models.CharField(max_length=50)),
                ('date', models.DateField(max_length=20)),
                ('quantity', models.IntegerField(default=0)),
                ('pid', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'sos_shoppingcart',
            },
        ),
        migrations.CreateModel(
            name='Staffmember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=50)),
                ('joiningDate', models.DateField(max_length=20)),
                ('division', models.CharField(max_length=50)),
                ('previousEmployer', models.CharField(max_length=50)),
                ('did', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'sos_staffmember',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('dob', models.DateField(max_length=20)),
                ('mobileNumber', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('college_ID', models.IntegerField()),
                ('collegeName', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'sos_student',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectName', models.CharField(max_length=50)),
                ('subjectDescription', models.CharField(max_length=50)),
                ('course_ID', models.IntegerField()),
                ('courseName', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'sos_subject',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDate', models.DateField(max_length=20)),
                ('taskTitle', models.CharField(max_length=50)),
                ('details', models.CharField(max_length=200)),
                ('assignTo', models.CharField(max_length=50)),
                ('taskStatus', models.CharField(max_length=50)),
                ('aid', models.IntegerField(default=0)),
                ('sid', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'sos_task',
            },
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examTime', models.CharField(max_length=40)),
                ('examDate', models.DateField()),
                ('subject_ID', models.IntegerField()),
                ('subjectName', models.CharField(max_length=50)),
                ('course_ID', models.IntegerField()),
                ('courseName', models.CharField(max_length=50)),
                ('semester', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'sos_timetable',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('login_id', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('confirmpassword', models.CharField(default='', max_length=20)),
                ('dob', models.DateField(max_length=20)),
                ('address', models.CharField(default='', max_length=50)),
                ('gender', models.CharField(default='', max_length=50)),
                ('mobilenumber', models.CharField(default='', max_length=50)),
                ('role_Id', models.IntegerField()),
                ('role_Name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'sos_user',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicleId', models.IntegerField()),
                ('vehicleName', models.CharField(max_length=50)),
                ('vehicleType', models.CharField(max_length=50)),
                ('purchaseDate', models.DateField(max_length=20)),
                ('buyerName', models.CharField(max_length=50)),
                ('tid', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'sos_vehicle',
            },
        ),
    ]
